### ISSUE TITLE
LaTeXные войны: Очепятки наносят ответный удар

### ISSUE THREAD

**Issue by BoloniniD** [LoDThe/hse-tex#13]
Я хз как оформлять ваши issue тут. Но вот опечатки которые я смог найти. По формулам хз, ща посмотрю.
<img width="508" alt="1" src="https://user-images.githubusercontent.com/54375878/74627643-97962380-5164-11ea-950f-d11ea7331163.png">
<img width="515" alt="2" src="https://user-images.githubusercontent.com/54375878/74627646-982eba00-5164-11ea-87c7-1c91271d4818.png">
<img width="500" alt="3" src="https://user-images.githubusercontent.com/54375878/74627647-98c75080-5164-11ea-83b6-137cc22470d9.png">
<img width="509" alt="4" src="https://user-images.githubusercontent.com/54375878/74627648-995fe700-5164-11ea-8cf2-5684e619fd01.png">
<img width="676" alt="5" src="https://user-images.githubusercontent.com/54375878/74627649-99f87d80-5164-11ea-9ceb-cc537a1a2d8f.png">
<img width="573" alt="6" src="https://user-images.githubusercontent.com/54375878/74627651-9a911400-5164-11ea-9c05-15c2a4f72158.png">

**Comment by BoloniniD** [comment]
Такие дела

**Comment by LoDThe** [comment]
Спасибо! Исправил :+1:

**Comment by BoloniniD** [comment]
Не буду новую открывать. "Предыущую" поменяли на "предудыщую". Все остальное ок, в матеше ошибок вроде нет.
