### ISSUE TITLE
Ошибка имени Boloninid

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#14]
![photo_2020-02-18_10-24-36](https://user-images.githubusercontent.com/26520464/74713102-e31a0180-5238-11ea-8cc2-cf47deb1c4eb.jpg)
Возможно, в доказательстве пункта (2) вместо f(x)+ g(x) имеется в виду f(x)*g(x)?

**Comment by BoloniniD** [comment]
Возможно не имеется.

**Comment by LoDThe** [comment]
Кажется, исправил. Спасибо :sunglasses:
