### ISSUE TITLE
Возможная опечатка в 5.1

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#16]
![Screenshot_2020-02-25-15-28-07-968_com google android apps docs](https://user-images.githubusercontent.com/26520464/75247740-aa070180-57e3-11ea-8563-82480cfb0d6e.png)

Я не понимаю сути этой леммы, возможно, имелось в виду объединение вместо пересечения и T1 вместо T2?

**Comment by LoDThe** [comment]
Спасибо, исправил.
