### ISSUE TITLE
Играем со шрифтами и еще кое-что

### ISSUE THREAD

**Issue by BoloniniD** [LoDThe/hse-tex#19]
Нашел несколько небольших опечаток.
<img width="332" alt="1" src="https://user-images.githubusercontent.com/54375878/75340114-e77e9400-58a2-11ea-88a1-7485ffcd7d44.png">
<img width="493" alt="2" src="https://user-images.githubusercontent.com/54375878/75340501-a6d34a80-58a3-11ea-8b2b-2665c9f8afdd.png">
<img width="364" alt="3" src="https://user-images.githubusercontent.com/54375878/75341041-a5565200-58a4-11ea-855f-0db55110f8bb.png">
<img width="347" alt="4" src="https://user-images.githubusercontent.com/54375878/75341177-ee0e0b00-58a4-11ea-94c1-a34e295b33a4.png">
<img width="498" alt="5" src="https://user-images.githubusercontent.com/54375878/75341676-fb77c500-58a5-11ea-928e-e2934c6959dc.png">

**Comment by BoloniniD** [comment]
Математику вплоть до 9 @shoraii прочекал вроде, дальше хз.

**Comment by LoDThe** [comment]
Спасибо! Исправил.
