### ISSUE TITLE
9.3 или 11.3?

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#20]
![изображение](https://user-images.githubusercontent.com/26520464/75376826-c12c1900-58e1-11ea-8640-b56297604beb.png)
![изображение](https://user-images.githubusercontent.com/26520464/75376877-d4d77f80-58e1-11ea-84c8-09f36ad4b655.png)
Площадь криволинейной трапеции и длина кривой в содержании и в самом материале в разных билетах.

**Comment by LoDThe** [comment]
Спасибо, исправил!
