### ISSUE TITLE
15. Равномощность отрезков, интервалов, лучей и прямых (явные биекции).

### ISSUE THREAD

**Issue by Klesomik** [LoDThe/hse-tex#25]
В теореме о биекции между [0; 1] и (0; 1) возможно допущена ошибка.
Точкам отрезка вида 1/a надо сопоставлять точки интервала вида 1/(a + 2).
Так как иначе 1/2 будет переходить в 1/3, но также 1 переходит в 1/3.

**Comment by LoDThe** [comment]
Исправил, спасибо!
