### ISSUE TITLE
Некоторые ошибки в типографии

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#3]
Обнаружены опечатки в техах к коллоквиуму по линалу
![m1](https://user-images.githubusercontent.com/26520464/69914964-dfa58400-145a-11ea-9caa-8d9b91f96bbd.PNG)
![m2](https://user-images.githubusercontent.com/26520464/69914967-e46a3800-145a-11ea-89f5-fc245d92cdd0.PNG)

**Comment by DarkKeks** [comment]
Спасибо, вместе с этим поправил еще доказательство 2.6
