### ISSUE TITLE
Опечатка в техе коллоквиума по ЛАиГ

### ISSUE THREAD

**Issue by ATGDeveloper** [LoDThe/hse-tex#32]
> Формула для ортогональной проекции вектора на подпространство в R
> 𝑛 в терминах его произвольного базиса

Непонятная нулевая степень матрицы M

**Comment by DarkKeks** [comment]
Это множество невырожденных квадратных матриц.
Обсуждалось на [18 лекции](https://photos.google.com/share/AF1QipMkYPA70PePjerTqO3xURo_P5ji1bYDRlmFOv3XdfN1qhbKZz1CG2GLVTcUZtd7VA/photo/AF1QipMtH2XfSwCQwDG5DglpxyeFronbJ0829GW-vqp4?key=VzF5SF9hVVc2amhhalhXNHJzMDZpbVlnOFBEUkpn) -- на ~ 19:10.

В конспекте есть как "обозначение 2" в пункте 18.4

**Comment by LoDThe** [comment]
:sunglasses:
