### ISSUE TITLE
Не поимаю, откуда берутся утверждения в 2.2.6 и 2.2.9

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#33]
![изображение](https://user-images.githubusercontent.com/26520464/82159272-bd32e600-9895-11ea-9007-ab9f2c943857.png)
![изображение](https://user-images.githubusercontent.com/26520464/82159276-c8861180-9895-11ea-8f90-486416cf0aff.png)

**Comment by DarkKeks** [comment]
))))))))))
