### ISSUE TITLE
Версия теха

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#34]
Добавьте на страницу коллоквиума версию теха плс

**Comment by DarkKeks** [comment]
Не очень понимаю что такое "версия теха", у меня на арче последний texlive:
```sh
❯ yay -Qe | grep texlive
texlive-bibtexextra 2019.52577-1
texlive-core 2019.52579-1
texlive-fontsextra 2019.52580-1
texlive-formatsextra 2019.51280-1
texlive-games 2019.52525-1
texlive-humanities 2019.52574-1
texlive-kbordermatrix 1-1
texlive-langcyrillic 2019.52494-1
texlive-latexextra 2019.52575-1
texlive-music 2019.52275-1
texlive-pictures 2019.52499-1
texlive-pstricks 2019.52550-1
texlive-publishers 2019.52538-1
texlive-science 2019.52582-1
```

Как завести texlive на убунте, можно подсмотреть в .travis.yml (в репозиториях убунты очень старый пакет, поэтому юзаем репо debian).

На винде кажется можно просто поставить texlive -- https://www.tug.org/texlive/windows.html

**Comment by shoraii** [comment]
Извиняюсь за неточность, под версией теха я имел в виду дату последнего изменения документа
![Screenshot_2020-05-22-00-17-16-872_com google android apps docs](https://user-images.githubusercontent.com/26520464/82607596-c091de80-9bc1-11ea-9c54-ab8f917f9126.png)

**Comment by DarkKeks** [comment]
![image](https://user-images.githubusercontent.com/13303874/82607784-28482980-9bc2-11ea-9e7f-f8630a155882.png)
