### ISSUE TITLE
Сердце не работает(

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#35]
2.4.11
![Screenshot_2020-05-21-23-58-25-528_com google android apps docs](https://user-images.githubusercontent.com/26520464/82606079-29c42280-9bbf-11ea-9b3c-807958ef8b27.png)

**Comment by LoDThe** [comment]
Прямой массаж сердца, срочно

**Comment by DarkKeks** [comment]
Странно, у меня работает (хром на десктопе и adobe acrobat на телефоне)
Ссылается правда чуть ниже чем хотелось бы, но рядом :D

Это в каком просмотрщике?

**Comment by shoraii** [comment]
Встроенный в Firefox на десктопе, действительно посылает ниже, чем нужно, нужно промотать наверх для просмотра.
