### ISSUE TITLE
Дополнение в ЛАИГ Коллоквиум II, теорема 2.5.5

### ISSUE THREAD

**Issue by LoDThe** [LoDThe/hse-tex#40]
Непонятно, о какой лемме идет речь. И лучше ее доказательство тоже добавить.
![image](https://user-images.githubusercontent.com/4996880/82838057-a747a580-9ed3-11ea-9c56-989554fcca56.png)

**Comment by DarkKeks** [comment]
Утверждение 4.1 в конспекте, было в первом коллке))
Это уже кажется лишним здесь, с таким же успехом можно весь линал добавлять..

**Comment by LoDThe** [comment]
Можно и добавить
