### ISSUE TITLE
2.6.1

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#44]
![изображение](https://user-images.githubusercontent.com/26520464/83065367-0cce9a00-a06c-11ea-9bd6-7db9ce25628d.png)

**Comment by DarkKeks** [comment]
Неочевидно почему 1) & 2) \iff 3) ?
Добавлю ссылку вот сюда:
![image](https://user-images.githubusercontent.com/13303874/83090649-eb88a080-a0a1-11ea-81c1-8ed7cbc5bd72.png)

**Comment by DarkKeks** [comment]
Ору, мне Игорь показал, я сам так и не заметил :DDDDDD

![image](https://user-images.githubusercontent.com/13303874/83156358-fe838b00-a10a-11ea-883c-c66c8e9c35dc.png)

Починил в следующем коммите
