### ISSUE TITLE
🧐

### ISSUE THREAD

**Issue by shoraii** [LoDThe/hse-tex#49]
![изображение](https://user-images.githubusercontent.com/26520464/83905512-76386200-a76a-11ea-908c-9f2f9e0c841c.png)
![изображение](https://user-images.githubusercontent.com/26520464/83905552-86504180-a76a-11ea-8a39-9ce868bf74fa.png)
![изображение](https://user-images.githubusercontent.com/26520464/83905563-8b14f580-a76a-11ea-8e48-ab8764a882e6.png)

**Comment by LoDThe** [comment]
Эта информация обновляется при каждом новом билде. Делать что-то умное слишком лень :( Поэтому эта информация актуальна для коллоквиума, который идет сейчас.
